name: Weekly CI
on:
  schedule:
    - cron: 0 0 * * 1 # At 00:00 on Monday

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest}
          - {os: windows-latest}

    name: Tests
    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
          shards: false

      - name: Run tests
        run: crystal spec
